[defaults]
width = 12
height = 16
dpi = 300
px_per_m_ref = 0.096
pad_inches = 0.00
distance = 30000
rotation = 0

# -------------------------------
# Road styles
# -------------------------------
[road_styles]
path           = { order = 0, theme_key = "road_track",         width = 0.1 }
track          = { order = 0, theme_key = "road_track",         width = 0.1 }
pedestrian     = { order = 0, theme_key = "road_track",         width = 0.1 }
footway        = { order = 0, theme_key = "road_track",         width = 0.1 }
cycleway       = { order = 0, theme_key = "road_track",         width = 0.1 }
service        = { order = 1, theme_key = "road_service",       width = 0.4 }
residential    = { order = 2, theme_key = "road_residential",   width = 0.4 }
living_street  = { order = 2, theme_key = "road_residential",   width = 0.4 }
unclassified   = { order = 2, theme_key = "road_residential",   width = 0.4 }
tertiary       = { order = 3, theme_key = "road_tertiary",      width = 0.6 }
tertiary_link  = { order = 3, theme_key = "road_tertiary",      width = 0.6 }
secondary      = { order = 4, theme_key = "road_secondary",     width = 0.8 }
secondary_link = { order = 4, theme_key = "road_secondary",     width = 0.8 }
primary        = { order = 5, theme_key = "road_primary",       width = 1.0 }
primary_link   = { order = 5, theme_key = "road_primary",       width = 1.0 }
trunk          = { order = 6, theme_key = "road_primary",       width = 1.0 }
trunk_link     = { order = 6, theme_key = "road_primary",       width = 1.0 }
motorway       = { order = 7, theme_key = "road_motorway",      width = 1.2 }
motorway_link  = { order = 7, theme_key = "road_motorway",      width = 1.2 }

# -------------------------------
# Layer configuration
# -------------------------------
[layers]
street_network = { fetch_func="fetch_graph",            zorder=0,    alpha=1,    color_theme_key=""}
water          = { fetch_func="fetch_features",         zorder=2,    alpha=1,    color_theme_key="water",                                                               tags_natural=["water","bay","strait"], tags_waterway=["riverbank","dock","canal"]}
wetland        = { fetch_func="fetch_features",         zorder=2,    alpha=1,    color_theme_key="wetland",         fallback_keys="water",                              tags_natural=["wetland"], tags_wetland=["marsh","bog","reedbed","swamp"]}
rivers         = { fetch_func="fetch_features",         zorder=3,    alpha=1,    color_theme_key="water",           linewidth=2.0,                                      tags_waterway=["river"]}
coastline      = { fetch_func="fetch_features",         zorder=3,    alpha=1,    color_theme_key="bg",                                                                  tags_natural="coastline"}
oceans         = { fetch_func="fetch_ocean_polygons",   zorder=0,    alpha=1,    color_theme_key="water",           depends_on=["coastline"]}
sand           = { fetch_func="fetch_features",         zorder=2,    alpha=1,    color_theme_key="sand",                                                                tags_natural=["beach","shoal","sand","desert","dune"]}
forests        = { fetch_func="fetch_features",         zorder=1,    alpha=1,    color_theme_key="forest",          fallback_keys="parks",                              tags_natural=["wood"], tags_landuse=["forest","logging","orchard"], tags_leisure=["nature_reserve"]}
grass          = { fetch_func="fetch_features",         zorder=1,    alpha=1,    color_theme_key="grass",           fallback_keys="parks",                              tags_natural=["grassland"], tags_landuse=["grass","recreation_ground","religious","village_green","greenery","greenfield","meadow","vineyard","cemetery"], tags_leisure=["park","garden", "golf_course"], tags_golf=["fairway"]}
farmland       = { fetch_func="fetch_features",         zorder=1,    alpha=1,    color_theme_key="farmland",        fallback_keys="parks",                              tags_landuse=["farmland","allotments"], tags_natural=["heath","scrub"]}
rocky          = { fetch_func="fetch_features",         zorder=1,    alpha=1,    color_theme_key="rocky",                                                               tags_landuse=["quarry","landfill","construction"], tags_natural=["bare_rock","scree","shingle","rock","stone"]}
zoning         = { fetch_func="fetch_features",         zorder=0,    alpha=1,    color_theme_key="zoning",                                                              tags_landuse=["residential","industrial","commercial","brownfield"], tags_amenity=["school", "college", "university"]}
railways       = { fetch_func="fetch_features",         zorder=6.2,  alpha=0.7,  color_theme_key="railway",         fallback_keys="road_primary",   linewidth=1.0,      tags_railway=["rail","narrow_gauge","monorail","light_rail"]}
subtram        = { fetch_func="fetch_features",         zorder=6,    alpha=0.7,  color_theme_key="subtram",         fallback_keys="road_primary",   linewidth=0.8,      tags_railway=["subway","funicular","tram"]}
aeroway        = { fetch_func="fetch_features",         zorder=3.5,  alpha=1,    color_theme_key="road_primary",                                    linewidth=0.6,      tags_aeroway=["runway","taxiway","apron"]}
buildings      = { fetch_func="fetch_features",         zorder=4,    alpha=0.5,  color_theme_key="building",        outline="building_outline",     linewidth=0.1,      tags_building=true}
